apiVersion: 1

# Datasource configuration
datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://pfa-prometheus:9090
    isDefault: true
    editable: true
    uid: prometheus